# Changes here will be overwritten by Copier
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: Adrian D'Alessandro
email: a.dalessandro@imperial.ac.uk
full_name: Adrian D'Alessandro
github_organization: AdrianDAlessandro
keywords: dessert,sweet
license: Apachev2
package_name: baklava
package_short_description: A sweet package
template_profile: minimum
version: 0.1.0
